name: Release
description: 'Release package'

inputs:
  GH_TOKEN:
    description: GH_TOKEN
    required: true
  NPM_TOKEN:
    description: NPM_TOKEN
    required: true


runs:
  using: "composite"
  steps:
    - name: Install dependencies # install project deps with --frozen-lockfile to make sure we will have the same packages version ( very recommended  on running yarn install on ci)
      shell: bash
      run: yarn release
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
