"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SCREENS = void 0;
var SCREENS;
(function (SCREENS) {
    SCREENS["Home"] = "Home";
    SCREENS["Settings"] = "Settings";
    SCREENS["Core"] = "Core";
    SCREENS["Calendar"] = "Calendar";
    SCREENS["Utils"] = "Utils";
    SCREENS["Chart"] = "Chart";
    SCREENS["Chat"] = "Chat";
    SCREENS["Controls"] = "Controls";
    SCREENS["CTA"] = "CTA";
    SCREENS["Inputs"] = "Inputs";
    SCREENS["Popups"] = "Popups";
    SCREENS["Progress"] = "Progress";
    SCREENS["Styles"] = "Styles";
    SCREENS["Typography"] = "Typography";
    SCREENS["Other"] = "Other";
    SCREENS["Navbars"] = "Navbars";
    SCREENS["LineChart"] = "LineChart";
    SCREENS["BarChart"] = "BarChart";
    SCREENS["KeyboardAware"] = "KeyboardAware";
    SCREENS["KeyboardAwareScrollView"] = "KeyboardAwareScrollView";
    SCREENS["KeyboardAwareScrollViewWithBottom"] = "KeyboardAwareScrollViewWithBottom";
    SCREENS["KeyboardAwareScrollViewTabs"] = "KeyboardAwareScrollViewTabsScreen";
    SCREENS["KeyboardAwareScrollViewWithTabs"] = "KeyboardAwareScrollViewWithTabs";
    SCREENS["KeyboardAwareScrollViewWithBottomAndTabs"] = "KeyboardAwareScrollViewWithBottomAndTabs";
    SCREENS["DragAndDrop"] = "DragAndDrop";
    SCREENS["Markdown"] = "Markdown";
})(SCREENS || (exports.SCREENS = SCREENS = {}));
