export const LABELS = {
  slider: 'slider',
  sliderLayoutLowThumb: 'sliderLayoutLowThumb',
  imageAvatar: 'imageAvatar',
  swipe: 'swipe',
  dotsAnimatedView: 'dotsAnimatedView',
  dotsScrollView: 'dotsScrollView',
  search: 'search',
  cancelSearch: 'cancelSearch',
  tab: 'tab',
  codeField: 'codeField',
  selector: 'selector',
  actionSheetsItem: 'actionSheetsItem',
  carousel: 'carousel',
  carouselItem: 'carouselItem',
  collapsed: 'collapsed',
  panelHeaderLeftView: 'panelHeaderLeftView',
  panelHeaderRightView: 'panelHeaderRightView',
};
